first commit, mobile nav
bckrm/airtec pull request #20
Opened 2021-06-03 21:33 UTC by kcbreuil

2021-06-04 17:59 UTC, asasmith commented
@kcbreuil do you have a specific question on this one? I thought you were going to try adding the classes we discussed this morning and see if that resolves the issue

2021-06-04 20:07 UTC, kcbreuil commented
@asasmith the placement of the button between 600-700px bothers me. I can't get it to move without destroying the placement of the hamburger nav div. Thoughts>

2021-06-07 12:41 UTC, asasmith requested changes
The close button needs a little work.

![Screen Shot 2021-06-07 at 8 41 30 AM](https://user-images.githubusercontent.com/11489171/121018190-2a007300-c76c-11eb-9b77-8cba4b98817d.png)

2021-06-07 12:41 UTC, asasmith commented on web/src/components/header.js
> +            <div className="container flex justify-between mx-auto text-white">
I don't think you need `mx-auto` here

2021-06-07 16:53 UTC, asasmith requested changes

2021-06-07 16:53 UTC, asasmith commented on web/src/components/navigation/mobileNav.js
> +    const thirdSpanLength = isMobileNavOpen ? 'w-10' : 'w-5';
Can these declarations be combined with the `*Styles` declarations?

2021-06-07 16:53 UTC, asasmith commented on web/src/components/navigation/mobileNav.js
> +                    className={`h-1 rounded-full transform-gpu w-11 transition transition-all duration-300 origin-right ${firstSpanStyles} ${colorStyle} ${firstSpanLength}`}
remove `w-11`

2021-06-07 17:32 UTC, asasmith commented on web/src/components/navigation/mobileNav.js
> +    const colorStyle = isMobileNavOpen ? 'bg-black' : 'bg-white';
can these be combined into the other span styles too?

2021-06-07 18:13 UTC, merged