certficiations section
bckrm/airtec pull request #34
Opened 2021-06-15 16:30 UTC by kcbreuil

- created certification card
- Created section
- have removed Section from About page, will push up after you have reviewed

2021-06-16 12:01 UTC, asasmith requested changes

2021-06-16 12:01 UTC, asasmith commented on web/src/components/certificationSection.js
> +        <div className="bg-brand-1 py-14 mb-2 text-white w-full">
Do you need `mb-2`?

2021-06-16 12:01 UTC, asasmith commented on web/src/components/certification.js
> +        <div className="odd:bg-white odd:bg-opacity-10 p-4 text-2xl">
Nice use of the `odd:` utility here!

2021-06-16 16:48 UTC, kcbreuil commented on web/src/components/certificationSection.js
> +                <h2 className="text-ts-h2 uppercase">Certifications</h2>
@asasmith i think this is a mistake actually, most headings are bolded. The designs are still pulling in Gallano and that is not correct

2021-06-16 16:56 UTC, kcbreuil commented on web/src/components/certificationSection.js
> +                <h2 className="text-ts-h2 uppercase">Certifications</h2>
@asasmith ok just confirmed, cross site we are keeping these specific headings unweighted. see news, history, leadership etc

2021-06-17 12:07 UTC, asasmith requested changes

2021-06-17 19:49 UTC, merged