add news item, add news carousel, add color props
bckrm/airtec pull request #44
Opened 2021-06-21 23:50 UTC by kcbreuil

2021-06-23 13:44 UTC, asasmith commented
There's a sharp line at the edge of the container. Might need to revisit your html structure.

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTg1Nzg5OGEtOThhNS00YjlhLWFjZjctZjdhMTA4OTZjZTVhIiwiZGVwbG95X2lkIjoiNjBkMTI3NzhmODRmMWQwMDA3NzliNzU4IiwiaWQiOiJhYWZiNjM0Yi01OTAxLTQ0ODctOWJiYy1jMjMxOGQxZTY0NTgifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /news-template/
Browser:   Chrome 91.0.4472.106 on Mac OS 10.15.7
Viewport:  1680 x 914 @2x
Language:  en-US
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-44--airtec.netlify.app%2Fnews-template%2F&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=91.0&resolution=1680x914&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-44--airtec.netlify.app/news-template/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60d12778f84f1d000779b758&commentID=60d33ad932e86e3e9c97cbbf&resolution=resolved)

2021-06-23 15:56 UTC, kcbreuil commented
@asasmith that is the container from the carousel, it's showing up because of the drop shadow. See below without shadow: 
<img width="876" alt="Screen Shot 2021-06-23 at 11 56 27 AM" src="https://user-images.githubusercontent.com/61708936/123129574-0d299800-d41a-11eb-9503-d2ea144a750d.png">

2021-06-29 01:39 UTC, asasmith commented
> @asasmith that is the container from the carousel, it's showing up because of the drop shadow. See below without shadow:
> <img alt="Screen Shot 2021-06-23 at 11 56 27 AM" width="876" src="https://user-images.githubusercontent.com/61708936/123129574-0d299800-d41a-11eb-9503-d2ea144a750d.png">

What about changing the overflow?

2021-06-29 01:49 UTC, asasmith requested changes

2021-06-29 01:49 UTC, asasmith commented on web/src/components/recentNewsList.js
> +    const text = 'More ❯';
`forward` might be a better variable name.

2021-06-29 01:49 UTC, asasmith commented on web/src/components/newsCard.js
> +            className="bg-white h-[34rem] mx-3 md:mr-9 transform transition	focus:scale-110 md:hover:scale-110 shadow-xl overflow-hidden w-80"
Remove extra spaces between `transition` and `focus`

2021-06-30 16:53 UTC, asasmith commented
Still seeing a very sharp and very defined line here

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTg1Nzg5OGEtOThhNS00YjlhLWFjZjctZjdhMTA4OTZjZTVhIiwiZGVwbG95X2lkIjoiNjBkYzlmNWUwOWNjMjMwMDA4ZWY4NDc5IiwiaWQiOiJiMzFlYmYwOS1kODg2LTQ3MzQtOWQzMC1lNzMzMzVkZWMzYjgifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /news-template/
Browser:   Chrome 91.0.4472.106 on Mac OS 10.15.7
Viewport:  1676 x 914 @2x
Language:  en-US
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-44--airtec.netlify.app%2Fnews-template%2F&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=91.0&resolution=1676x914&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-44--airtec.netlify.app/news-template/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60dc9f5e09cc230008ef8479&commentID=60dca18e46c3a155a0a40a40&resolution=resolved)

2021-07-01 01:58 UTC, merged